services:
  - type: web
    name: nxtcure-app
    env: python
    # Python version is set via runtime.txt (python-3.10.13)
    buildCommand: npm install && npm run build && pip install -r requirements-simple.txt
    startCommand: python backend/main.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
    rootDir: nxtcure-frontend 